GET http://localhost:8080/api/products

###
GET http://localhost:8080/api/products/1

###
GET http://localhost:8080/api/products?page=5&size=10

###
GET http://localhost:8080/api/product-category

###
GET http://localhost:8080/api/product-category/1

###
GET http://localhost:8080/api/products/search/findByCategoryId?id=1

###
GET http://localhost:8080/api/products/search/findByNameContaining?name=Data


###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "TEST123",
  "name": "Produit Test",
  "description": "Un produit de test",
  "unitPrice": 99.99,
  "imageUrl": "http://example.com/test.jpg",
  "active": true,
  "unitsInStock": 10,
  "category": "http://localhost:8080/api/product-category/1"
}
